### ISSUE TITLE
Editing newly created copy of existing meal causes app crash

### ISSUE THREAD

**Issue by st1hy** [st1hy/Red-Calorie#32]
Steps to reproduce on 1.5.6:

1. Copy a meal to today
2. Edit this mel
3. Click save

Application crashes on Android Oreo:
Crash report is not uploading to Play Services, no errors are reported to Logcat (Android 8.0 only)
Under investigation (manual error logging) problem was found in:

`09-29 22:52:59.150 2426-2493/? E/AddMealPresenterImp$$La: org.greenrobot.greendao.DaoException: Entity is detached from DAO context
                                                              at com.github.st1hy.countthemcalories.database.IngredientTemplate.getChildIngredients(IngredientTemplate.java:164)
                                                              at com.github.st1hy.countthemcalories.activities.overview.meals.model.RxMealsDatabaseModel.performInsertOrUpdate(RxMealsDatabaseModel.java:69)
                                                              at com.github.st1hy.countthemcalories.activities.overview.meals.model.RxMealsDatabaseModel.lambda$insertOrUpdate$1(RxMealsDatabaseModel.java:58)
                                                              at com.github.st1hy.countthemcalories.activities.overview.meals.model.RxMealsDatabaseModel$$Lambda$2.call(Unknown Source:0)
                                                              at org.greenrobot.greendao.AbstractDaoSession.callInTx(AbstractDaoSession.java:166)
                                                              at com.github.st1hy.countthemcalories.core.rx.AbstractRxDatabaseModel.lambda$callInTx$0(AbstractRxDatabaseModel.java:32)
                                                              at com.github.st1hy.countthemcalories.core.rx.AbstractRxDatabaseModel$$Lambda$1.call(Unknown Source:0)
                                                              at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
                                                              at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
                                                              at rx.Observable.unsafeSubscribe(Observable.java:10346)
                                                              at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
                                                              at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
                                                              at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                              at java.lang.Thread.run(Thread.java:764)`

**Comment by st1hy** [comment]
29b2f9b678d4b8e1f6481a180e6e0a4310d792f3
